/**
 * @fileoverview This file is generated by the Angular 2 template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from '../../../app/store/store.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/forms/src/directives';
import * as import6 from '@angular/forms/src/form_providers';
import * as import7 from '@angular/router/src/router_module';
import * as import8 from '@angular/http/src/http_module';
import * as import9 from '../../../app/model/model.module';
import * as import10 from '@angular/common/src/localization';
import * as import11 from '@angular/core/src/application_init';
import * as import12 from '@angular/core/src/testability/testability';
import * as import13 from '@angular/core/src/application_ref';
import * as import14 from '@angular/core/src/linker/compiler';
import * as import15 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import16 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import17 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import18 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import19 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import20 from '@angular/core/src/linker/view_utils';
import * as import21 from '@angular/platform-browser/src/browser/title';
import * as import22 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import23 from '@angular/http/src/backends/browser_xhr';
import * as import24 from '@angular/http/src/base_response_options';
import * as import25 from '@angular/http/src/backends/xhr_backend';
import * as import26 from '@angular/http/src/base_request_options';
import * as import27 from '../../../app/model/rest.datasource';
import * as import28 from '../../../app/model/product.repository';
import * as import29 from '../../../app/model/cart.model';
import * as import30 from '../../../app/model/order.model';
import * as import31 from '../../../app/model/order.repository';
import * as import32 from '../../../app/model/auth.service';
import * as import33 from '@angular/core/src/di/injector';
import * as import34 from '@angular/core/src/application_tokens';
import * as import35 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import36 from '@angular/platform-browser/src/dom/events/key_events';
import * as import37 from '@angular/core/src/zone/ng_zone';
import * as import38 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import39 from '@angular/core/src/console';
import * as import40 from '@angular/core/src/i18n/tokens';
import * as import41 from '@angular/core/src/error_handler';
import * as import42 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import43 from '@angular/platform-browser/src/dom/animation_driver';
import * as import44 from '@angular/core/src/render/api';
import * as import45 from '@angular/core/src/security';
import * as import46 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import47 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import48 from '@angular/http/src/interfaces';
import * as import49 from '@angular/http/src/http';
class StoreModuleInjector extends import0.NgModuleInjector<import1.StoreModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _InternalFormsSharedModule_3:import5.InternalFormsSharedModule;
  _FormsModule_4:import6.FormsModule;
  _RouterModule_5:import7.RouterModule;
  _HttpModule_6:import8.HttpModule;
  _ModelModule_7:import9.ModelModule;
  _StoreModule_8:import1.StoreModule;
  __LOCALE_ID_9:any;
  __NgLocalization_10:import10.NgLocaleLocalization;
  _ErrorHandler_11:any;
  _ApplicationInitStatus_12:import11.ApplicationInitStatus;
  _Testability_13:import12.Testability;
  _ApplicationRef__14:import13.ApplicationRef_;
  __ApplicationRef_15:any;
  __Compiler_16:import14.Compiler;
  __APP_ID_17:any;
  __DOCUMENT_18:any;
  __HAMMER_GESTURE_CONFIG_19:import15.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_20:any[];
  __EventManager_21:import16.EventManager;
  __DomSharedStylesHost_22:import17.DomSharedStylesHost;
  __AnimationDriver_23:any;
  __DomRootRenderer_24:import18.DomRootRenderer_;
  __RootRenderer_25:any;
  __DomSanitizer_26:import19.DomSanitizerImpl;
  __Sanitizer_27:any;
  __ViewUtils_28:import20.ViewUtils;
  __IterableDiffers_29:any;
  __KeyValueDiffers_30:any;
  __SharedStylesHost_31:any;
  __Title_32:import21.Title;
  __RadioControlRegistry_33:import22.RadioControlRegistry;
  __BrowserXhr_34:import23.BrowserXhr;
  __ResponseOptions_35:import24.BaseResponseOptions;
  __XSRFStrategy_36:any;
  __XHRBackend_37:import25.XHRBackend;
  __RequestOptions_38:import26.BaseRequestOptions;
  __Http_39:any;
  __RestDataSource_40:import27.RestDataSource;
  __ProductRepository_41:import28.ProductRepository;
  __Cart_42:import29.Cart;
  __Order_43:import30.Order;
  __OrderRepository_44:import31.OrderRepository;
  __AuthService_45:import32.AuthService;
  constructor(parent:import33.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _LOCALE_ID_9():any {
    if ((this.__LOCALE_ID_9 == null)) { (this.__LOCALE_ID_9 = 'en-US'); }
    return this.__LOCALE_ID_9;
  }
  get _NgLocalization_10():import10.NgLocaleLocalization {
    if ((this.__NgLocalization_10 == null)) { (this.__NgLocalization_10 = new import10.NgLocaleLocalization(this._LOCALE_ID_9)); }
    return this.__NgLocalization_10;
  }
  get _ApplicationRef_15():any {
    if ((this.__ApplicationRef_15 == null)) { (this.__ApplicationRef_15 = this._ApplicationRef__14); }
    return this.__ApplicationRef_15;
  }
  get _Compiler_16():import14.Compiler {
    if ((this.__Compiler_16 == null)) { (this.__Compiler_16 = new import14.Compiler()); }
    return this.__Compiler_16;
  }
  get _APP_ID_17():any {
    if ((this.__APP_ID_17 == null)) { (this.__APP_ID_17 = import34._appIdRandomProviderFactory()); }
    return this.__APP_ID_17;
  }
  get _DOCUMENT_18():any {
    if ((this.__DOCUMENT_18 == null)) { (this.__DOCUMENT_18 = import4._document()); }
    return this.__DOCUMENT_18;
  }
  get _HAMMER_GESTURE_CONFIG_19():import15.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_19 == null)) { (this.__HAMMER_GESTURE_CONFIG_19 = new import15.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_19;
  }
  get _EVENT_MANAGER_PLUGINS_20():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_20 == null)) { (this.__EVENT_MANAGER_PLUGINS_20 = [
      new import35.DomEventsPlugin(),
      new import36.KeyEventsPlugin(),
      new import15.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_19)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_20;
  }
  get _EventManager_21():import16.EventManager {
    if ((this.__EventManager_21 == null)) { (this.__EventManager_21 = new import16.EventManager(this._EVENT_MANAGER_PLUGINS_20,this.parent.get(import37.NgZone))); }
    return this.__EventManager_21;
  }
  get _DomSharedStylesHost_22():import17.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_22 == null)) { (this.__DomSharedStylesHost_22 = new import17.DomSharedStylesHost(this._DOCUMENT_18)); }
    return this.__DomSharedStylesHost_22;
  }
  get _AnimationDriver_23():any {
    if ((this.__AnimationDriver_23 == null)) { (this.__AnimationDriver_23 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_23;
  }
  get _DomRootRenderer_24():import18.DomRootRenderer_ {
    if ((this.__DomRootRenderer_24 == null)) { (this.__DomRootRenderer_24 = new import18.DomRootRenderer_(this._DOCUMENT_18,this._EventManager_21,this._DomSharedStylesHost_22,this._AnimationDriver_23,this._APP_ID_17)); }
    return this.__DomRootRenderer_24;
  }
  get _RootRenderer_25():any {
    if ((this.__RootRenderer_25 == null)) { (this.__RootRenderer_25 = import38._createConditionalRootRenderer(this._DomRootRenderer_24,this.parent.get(import38.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_25;
  }
  get _DomSanitizer_26():import19.DomSanitizerImpl {
    if ((this.__DomSanitizer_26 == null)) { (this.__DomSanitizer_26 = new import19.DomSanitizerImpl()); }
    return this.__DomSanitizer_26;
  }
  get _Sanitizer_27():any {
    if ((this.__Sanitizer_27 == null)) { (this.__Sanitizer_27 = this._DomSanitizer_26); }
    return this.__Sanitizer_27;
  }
  get _ViewUtils_28():import20.ViewUtils {
    if ((this.__ViewUtils_28 == null)) { (this.__ViewUtils_28 = new import20.ViewUtils(this._RootRenderer_25,this._Sanitizer_27)); }
    return this.__ViewUtils_28;
  }
  get _IterableDiffers_29():any {
    if ((this.__IterableDiffers_29 == null)) { (this.__IterableDiffers_29 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_29;
  }
  get _KeyValueDiffers_30():any {
    if ((this.__KeyValueDiffers_30 == null)) { (this.__KeyValueDiffers_30 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_30;
  }
  get _SharedStylesHost_31():any {
    if ((this.__SharedStylesHost_31 == null)) { (this.__SharedStylesHost_31 = this._DomSharedStylesHost_22); }
    return this.__SharedStylesHost_31;
  }
  get _Title_32():import21.Title {
    if ((this.__Title_32 == null)) { (this.__Title_32 = new import21.Title()); }
    return this.__Title_32;
  }
  get _RadioControlRegistry_33():import22.RadioControlRegistry {
    if ((this.__RadioControlRegistry_33 == null)) { (this.__RadioControlRegistry_33 = new import22.RadioControlRegistry()); }
    return this.__RadioControlRegistry_33;
  }
  get _BrowserXhr_34():import23.BrowserXhr {
    if ((this.__BrowserXhr_34 == null)) { (this.__BrowserXhr_34 = new import23.BrowserXhr()); }
    return this.__BrowserXhr_34;
  }
  get _ResponseOptions_35():import24.BaseResponseOptions {
    if ((this.__ResponseOptions_35 == null)) { (this.__ResponseOptions_35 = new import24.BaseResponseOptions()); }
    return this.__ResponseOptions_35;
  }
  get _XSRFStrategy_36():any {
    if ((this.__XSRFStrategy_36 == null)) { (this.__XSRFStrategy_36 = import8._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_36;
  }
  get _XHRBackend_37():import25.XHRBackend {
    if ((this.__XHRBackend_37 == null)) { (this.__XHRBackend_37 = new import25.XHRBackend(this._BrowserXhr_34,this._ResponseOptions_35,this._XSRFStrategy_36)); }
    return this.__XHRBackend_37;
  }
  get _RequestOptions_38():import26.BaseRequestOptions {
    if ((this.__RequestOptions_38 == null)) { (this.__RequestOptions_38 = new import26.BaseRequestOptions()); }
    return this.__RequestOptions_38;
  }
  get _Http_39():any {
    if ((this.__Http_39 == null)) { (this.__Http_39 = import8.httpFactory(this._XHRBackend_37,this._RequestOptions_38)); }
    return this.__Http_39;
  }
  get _RestDataSource_40():import27.RestDataSource {
    if ((this.__RestDataSource_40 == null)) { (this.__RestDataSource_40 = new import27.RestDataSource(this._Http_39)); }
    return this.__RestDataSource_40;
  }
  get _ProductRepository_41():import28.ProductRepository {
    if ((this.__ProductRepository_41 == null)) { (this.__ProductRepository_41 = new import28.ProductRepository(this._RestDataSource_40)); }
    return this.__ProductRepository_41;
  }
  get _Cart_42():import29.Cart {
    if ((this.__Cart_42 == null)) { (this.__Cart_42 = new import29.Cart()); }
    return this.__Cart_42;
  }
  get _Order_43():import30.Order {
    if ((this.__Order_43 == null)) { (this.__Order_43 = new import30.Order(this._Cart_42)); }
    return this.__Order_43;
  }
  get _OrderRepository_44():import31.OrderRepository {
    if ((this.__OrderRepository_44 == null)) { (this.__OrderRepository_44 = new import31.OrderRepository(this._RestDataSource_40)); }
    return this.__OrderRepository_44;
  }
  get _AuthService_45():import32.AuthService {
    if ((this.__AuthService_45 == null)) { (this.__AuthService_45 = new import32.AuthService(this._RestDataSource_40)); }
    return this.__AuthService_45;
  }
  createInternal():import1.StoreModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._InternalFormsSharedModule_3 = new import5.InternalFormsSharedModule();
    this._FormsModule_4 = new import6.FormsModule();
    this._RouterModule_5 = new import7.RouterModule(this.parent.get(import7.ROUTER_FORROOT_GUARD,(null as any)));
    this._HttpModule_6 = new import8.HttpModule();
    this._ModelModule_7 = new import9.ModelModule();
    this._StoreModule_8 = new import1.StoreModule();
    this._ErrorHandler_11 = import4.errorHandler();
    this._ApplicationInitStatus_12 = new import11.ApplicationInitStatus(this.parent.get(import11.APP_INITIALIZER,(null as any)));
    this._Testability_13 = new import12.Testability(this.parent.get(import37.NgZone));
    this._ApplicationRef__14 = new import13.ApplicationRef_(this.parent.get(import37.NgZone),this.parent.get(import39.Console),this,this._ErrorHandler_11,this,this._ApplicationInitStatus_12,this.parent.get(import12.TestabilityRegistry,(null as any)),this._Testability_13);
    return this._StoreModule_8;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_3; }
    if ((token === import6.FormsModule)) { return this._FormsModule_4; }
    if ((token === import7.RouterModule)) { return this._RouterModule_5; }
    if ((token === import8.HttpModule)) { return this._HttpModule_6; }
    if ((token === import9.ModelModule)) { return this._ModelModule_7; }
    if ((token === import1.StoreModule)) { return this._StoreModule_8; }
    if ((token === import40.LOCALE_ID)) { return this._LOCALE_ID_9; }
    if ((token === import10.NgLocalization)) { return this._NgLocalization_10; }
    if ((token === import41.ErrorHandler)) { return this._ErrorHandler_11; }
    if ((token === import11.ApplicationInitStatus)) { return this._ApplicationInitStatus_12; }
    if ((token === import12.Testability)) { return this._Testability_13; }
    if ((token === import13.ApplicationRef_)) { return this._ApplicationRef__14; }
    if ((token === import13.ApplicationRef)) { return this._ApplicationRef_15; }
    if ((token === import14.Compiler)) { return this._Compiler_16; }
    if ((token === import34.APP_ID)) { return this._APP_ID_17; }
    if ((token === import42.DOCUMENT)) { return this._DOCUMENT_18; }
    if ((token === import15.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_19; }
    if ((token === import16.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_20; }
    if ((token === import16.EventManager)) { return this._EventManager_21; }
    if ((token === import17.DomSharedStylesHost)) { return this._DomSharedStylesHost_22; }
    if ((token === import43.AnimationDriver)) { return this._AnimationDriver_23; }
    if ((token === import18.DomRootRenderer)) { return this._DomRootRenderer_24; }
    if ((token === import44.RootRenderer)) { return this._RootRenderer_25; }
    if ((token === import19.DomSanitizer)) { return this._DomSanitizer_26; }
    if ((token === import45.Sanitizer)) { return this._Sanitizer_27; }
    if ((token === import20.ViewUtils)) { return this._ViewUtils_28; }
    if ((token === import46.IterableDiffers)) { return this._IterableDiffers_29; }
    if ((token === import47.KeyValueDiffers)) { return this._KeyValueDiffers_30; }
    if ((token === import17.SharedStylesHost)) { return this._SharedStylesHost_31; }
    if ((token === import21.Title)) { return this._Title_32; }
    if ((token === import22.RadioControlRegistry)) { return this._RadioControlRegistry_33; }
    if ((token === import23.BrowserXhr)) { return this._BrowserXhr_34; }
    if ((token === import24.ResponseOptions)) { return this._ResponseOptions_35; }
    if ((token === import48.XSRFStrategy)) { return this._XSRFStrategy_36; }
    if ((token === import25.XHRBackend)) { return this._XHRBackend_37; }
    if ((token === import26.RequestOptions)) { return this._RequestOptions_38; }
    if ((token === import49.Http)) { return this._Http_39; }
    if ((token === import27.RestDataSource)) { return this._RestDataSource_40; }
    if ((token === import28.ProductRepository)) { return this._ProductRepository_41; }
    if ((token === import29.Cart)) { return this._Cart_42; }
    if ((token === import30.Order)) { return this._Order_43; }
    if ((token === import31.OrderRepository)) { return this._OrderRepository_44; }
    if ((token === import32.AuthService)) { return this._AuthService_45; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__14.ngOnDestroy();
  }
}
export const StoreModuleNgFactory:import0.NgModuleFactory<import1.StoreModule> = new import0.NgModuleFactory(StoreModuleInjector,import1.StoreModule);